version: '2'

services:
  zookeeper:
    image: 'bitnami/zookeeper:latest'
    ports:
      - '2181:2181'
    volumes:
      - 'zookeeper_data:/bitnami'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    image: 'bitnami/kafka:latest'
    ports:
      - '9092:9092'
    volumes:
      - 'kafka_data:/bitnami'
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=LIST_HOST:PLAINTEXT
      - KAFKA_CFG_LISTENERS=LIST_HOST://0.0.0.0:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=LIST_HOST://192.168.99.100:9092
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=LIST_HOST
    depends_on:
      - zookeeper
  connect:
    image: debezium/connect:latest
    ports:
     - 8083:8083
     - 5005:5005
    environment:
     - BOOTSTRAP_SERVERS=kafka:9092
     - GROUP_ID=1
     - CONFIG_STORAGE_TOPIC=my_connect_configs
     - OFFSET_STORAGE_TOPIC=my_connect_offsets
     - STATUS_STORAGE_TOPIC=my_source_connect_statuses
    depends_on:
      - zookeeper
      - kafka
volumes:
  zookeeper_data:
    driver: local
  kafka_data:
    driver: local
